export enum ManagedProviderOperationState {
  RESERVED = 'RESERVED',
  USAGE_PENDING = 'USAGE_PENDING',
  USAGE_ACCEPTED = 'USAGE_ACCEPTED',
  USAGE_SETTLED = 'USAGE_SETTLED',
  RELEASED = 'RELEASED',
  RECONCILIATION_REQUIRED = 'RECONCILIATION_REQUIRED',
}
