import { defineIndex } from 'twenty-sdk/define';

import {
  SOCIAL_CONVERSATION_ACCOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_ACCOUNT_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_OBJECT_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_PROVIDER_CONVERSATION_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_PROVIDER_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_PROVIDER_IDENTITY_INDEX_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_CONVERSATION_PROVIDER_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier:
    SOCIAL_CONVERSATION_PROVIDER_IDENTITY_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: SOCIAL_CONVERSATION_OBJECT_UNIVERSAL_IDENTIFIER,
  isUnique: true,
  fields: [
    {
      universalIdentifier:
        SOCIAL_CONVERSATION_PROVIDER_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_CONVERSATION_PROVIDER_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        SOCIAL_CONVERSATION_ACCOUNT_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_CONVERSATION_ACCOUNT_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        SOCIAL_CONVERSATION_PROVIDER_CONVERSATION_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_CONVERSATION_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER,
    },
  ],
});
