import { defineIndex } from 'twenty-sdk/define';

import {
  SOCIAL_MESSAGE_CONVERSATION_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_CONVERSATION_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_PROVIDER_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_PROVIDER_IDENTITY_INDEX_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_PROVIDER_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
  SOCIAL_MESSAGE_PROVIDER_MESSAGE_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineIndex({
  universalIdentifier:
    SOCIAL_MESSAGE_PROVIDER_IDENTITY_INDEX_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: SOCIAL_MESSAGE_OBJECT_UNIVERSAL_IDENTIFIER,
  isUnique: true,
  fields: [
    {
      universalIdentifier:
        SOCIAL_MESSAGE_PROVIDER_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_MESSAGE_PROVIDER_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        SOCIAL_MESSAGE_CONVERSATION_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_MESSAGE_CONVERSATION_FIELD_UNIVERSAL_IDENTIFIER,
    },
    {
      universalIdentifier:
        SOCIAL_MESSAGE_PROVIDER_MESSAGE_ID_INDEX_FIELD_UNIVERSAL_IDENTIFIER,
      fieldUniversalIdentifier:
        SOCIAL_MESSAGE_PROVIDER_ID_FIELD_UNIVERSAL_IDENTIFIER,
    },
  ],
});
