export const CAMPAIGN_SEQUENCE_AUTHORITY_PORT = Symbol(
  'CAMPAIGN_SEQUENCE_AUTHORITY_PORT',
);
export const CAMPAIGN_EXECUTION_PERSISTENCE_PORT = Symbol(
  'CAMPAIGN_EXECUTION_PERSISTENCE_PORT',
);
export const CAMPAIGN_CAPACITY_TIME_ZONE_READER_PORT = Symbol(
  'CAMPAIGN_CAPACITY_TIME_ZONE_READER_PORT',
);
export const CAMPAIGN_EXECUTION_PLAN_READER_PORT = Symbol(
  'CAMPAIGN_EXECUTION_PLAN_READER_PORT',
);
export const CAMPAIGN_NEW_ACTIVATION_REVIEW_PORT = Symbol(
  'CAMPAIGN_NEW_ACTIVATION_REVIEW_PORT',
);
export const CAMPAIGN_EXECUTION_HISTORY_PORT = Symbol(
  'CAMPAIGN_EXECUTION_HISTORY_PORT',
);
export const CAMPAIGN_INITIAL_DUE_TIME_PORT = Symbol(
  'CAMPAIGN_INITIAL_DUE_TIME_PORT',
);
export const CAMPAIGN_EXECUTION_IDENTITY_PORT = Symbol(
  'CAMPAIGN_EXECUTION_IDENTITY_PORT',
);
export const CAMPAIGN_LIFECYCLE_ACTOR_PERMISSION_RESOLVER_PORT = Symbol(
  'CAMPAIGN_LIFECYCLE_ACTOR_PERMISSION_RESOLVER_PORT',
);
export const CAMPAIGN_LIFECYCLE_WRITE_AUTHORIZATION_PORT = Symbol(
  'CAMPAIGN_LIFECYCLE_WRITE_AUTHORIZATION_PORT',
);
export const CAMPAIGN_PROGRESSION_PORT = Symbol('CAMPAIGN_PROGRESSION_PORT');
export const CAMPAIGN_OCCURRENCE_CLAIM_PORT = Symbol(
  'CAMPAIGN_OCCURRENCE_CLAIM_PORT',
);
export const CAMPAIGN_SYSTEM_AUTHORITY_PORT = Symbol(
  'CAMPAIGN_SYSTEM_AUTHORITY_PORT',
);
export const CAMPAIGN_FINAL_SUBMISSION_AUTHORITY_PORT = Symbol(
  'CAMPAIGN_FINAL_SUBMISSION_AUTHORITY_PORT',
);
export const CAMPAIGN_SENT_PROJECTION_PORT = Symbol(
  'CAMPAIGN_SENT_PROJECTION_PORT',
);
export const CAMPAIGN_REPLY_EVIDENCE_PORT = Symbol(
  'CAMPAIGN_REPLY_EVIDENCE_PORT',
);
export const OUTBOUND_EMAIL_DISPATCH_TRANSACTION_PORT = Symbol(
  'OUTBOUND_EMAIL_DISPATCH_TRANSACTION_PORT',
);
export const SUSPEND_AWARE_MONOTONIC_CLOCK_PORT = Symbol(
  'SUSPEND_AWARE_MONOTONIC_CLOCK_PORT',
);
