import { type QueryRunner } from 'typeorm';

import { RegisteredInstanceCommand } from 'src/engine/core-modules/upgrade/decorators/registered-instance-command.decorator';
import { type FastInstanceCommand } from 'src/engine/core-modules/upgrade/interfaces/fast-instance-command.interface';

@RegisteredInstanceCommand('2.20.0', 1789313971536)
export class AddCampaignOperatorExclusionReasonFastInstanceCommand implements FastInstanceCommand {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE core."campaignOccurrence" DROP CONSTRAINT "CHK_CO_TERMINAL_SHAPE"`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignEnrollment" DROP CONSTRAINT "CHK_CEN_TERMINAL_SHAPE"`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignOccurrence" ADD CONSTRAINT "CHK_CO_TERMINAL_SHAPE" CHECK (COALESCE(((state IN ('PENDING','IN_FLIGHT','UNKNOWN')) AND "holdReason" IS NULL AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state='HELD' AND "holdReason" IN ('WORKSPACE_NOT_ACTIVE', 'ATTACHMENTS_UNAVAILABLE', 'MATERIAL_STALE', 'SENDER_POOL_STALE', 'SENDER_NOT_READY', 'CAPACITY_CONFIGURATION_INVALID', 'THREAD_EVIDENCE_MISSING', 'THREAD_EVIDENCE_AMBIGUOUS', 'THREAD_SENDER_CHANGED', 'DEFINITELY_UNACCEPTED_REVIEW', 'PROJECTION_RECONCILIATION_REQUIRED', 'DISPATCH_CONTRACT_CONFLICT') AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state IN ('SUCCEEDED','SKIPPED','CANCELLED') AND "holdReason" IS NULL AND "terminalReason" IN ('PROVIDER_ACCEPTED', 'CREATOR_MISSING', 'CREATOR_DELETED', 'CAMPAIGN_CREATOR_MISSING', 'CAMPAIGN_CREATOR_DELETED', 'INVALID_STAGE', 'NON_EMAIL_CONTACT_METHOD', 'INVALID_EMAIL', 'DUPLICATE_CREATOR_EMAIL', 'SUPPRESSED_EMAIL', 'CAMPAIGN_PAUSED', 'CAMPAIGN_COMPLETED', 'AUTHORIZATION_REVOKED', 'ENROLLMENT_REPLIED', 'SUPERSEDED_BY_WORKFLOW_VERSION', 'OPERATOR_EXCLUDED') AND "terminalAt" IS NOT NULL), FALSE))`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignEnrollment" ADD CONSTRAINT "CHK_CEN_TERMINAL_SHAPE" CHECK (COALESCE((state='ACTIVE' AND ("holdReason" IS NULL OR "holdReason" IN ('WORKSPACE_NOT_ACTIVE', 'ATTACHMENTS_UNAVAILABLE', 'MATERIAL_STALE', 'SENDER_POOL_STALE', 'SENDER_NOT_READY', 'CAPACITY_CONFIGURATION_INVALID', 'THREAD_EVIDENCE_MISSING', 'THREAD_EVIDENCE_AMBIGUOUS', 'THREAD_SENDER_CHANGED', 'DEFINITELY_UNACCEPTED_REVIEW', 'PROJECTION_RECONCILIATION_REQUIRED', 'DISPATCH_CONTRACT_CONFLICT')) AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state IN ('REPLIED','EXCLUDED','FINISHED') AND "holdReason" IS NULL AND "terminalReason" IN ('REPLY_RECEIVED', 'CREATOR_MISSING', 'CREATOR_DELETED', 'CAMPAIGN_CREATOR_MISSING', 'CAMPAIGN_CREATOR_DELETED', 'INVALID_STAGE', 'NON_EMAIL_CONTACT_METHOD', 'INVALID_EMAIL', 'DUPLICATE_CREATOR_EMAIL', 'SUPPRESSED_EMAIL', 'SEQUENCE_COMPLETED', 'NO_USABLE_AUTHORED_MESSAGE', 'OPERATOR_EXCLUDED') AND "terminalAt" IS NOT NULL AND (state <> 'FINISHED' OR "nextAuthoredMessageIndex"="authoredMessageCount")), FALSE))`,
    );
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    const used = await queryRunner.query(
      `SELECT 1 FROM core."campaignOccurrence" WHERE "terminalReason"='OPERATOR_EXCLUDED' UNION ALL SELECT 1 FROM core."campaignEnrollment" WHERE "terminalReason"='OPERATOR_EXCLUDED' LIMIT 1`,
    );
    if (!Array.isArray(used) || used.length > 0)
      throw new Error('Cannot remove retained operator exclusion evidence');
    await queryRunner.query(
      `ALTER TABLE core."campaignOccurrence" DROP CONSTRAINT "CHK_CO_TERMINAL_SHAPE"`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignEnrollment" DROP CONSTRAINT "CHK_CEN_TERMINAL_SHAPE"`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignOccurrence" ADD CONSTRAINT "CHK_CO_TERMINAL_SHAPE" CHECK (COALESCE(((state IN ('PENDING','IN_FLIGHT','UNKNOWN')) AND "holdReason" IS NULL AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state='HELD' AND "holdReason" IN ('WORKSPACE_NOT_ACTIVE', 'ATTACHMENTS_UNAVAILABLE', 'MATERIAL_STALE', 'SENDER_POOL_STALE', 'SENDER_NOT_READY', 'CAPACITY_CONFIGURATION_INVALID', 'THREAD_EVIDENCE_MISSING', 'THREAD_EVIDENCE_AMBIGUOUS', 'THREAD_SENDER_CHANGED', 'DEFINITELY_UNACCEPTED_REVIEW', 'PROJECTION_RECONCILIATION_REQUIRED', 'DISPATCH_CONTRACT_CONFLICT') AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state IN ('SUCCEEDED','SKIPPED','CANCELLED') AND "holdReason" IS NULL AND "terminalReason" IN ('PROVIDER_ACCEPTED', 'CREATOR_MISSING', 'CREATOR_DELETED', 'CAMPAIGN_CREATOR_MISSING', 'CAMPAIGN_CREATOR_DELETED', 'INVALID_STAGE', 'NON_EMAIL_CONTACT_METHOD', 'INVALID_EMAIL', 'DUPLICATE_CREATOR_EMAIL', 'SUPPRESSED_EMAIL', 'CAMPAIGN_PAUSED', 'CAMPAIGN_COMPLETED', 'AUTHORIZATION_REVOKED', 'ENROLLMENT_REPLIED', 'SUPERSEDED_BY_WORKFLOW_VERSION') AND "terminalAt" IS NOT NULL), FALSE))`,
    );
    await queryRunner.query(
      `ALTER TABLE core."campaignEnrollment" ADD CONSTRAINT "CHK_CEN_TERMINAL_SHAPE" CHECK (COALESCE((state='ACTIVE' AND ("holdReason" IS NULL OR "holdReason" IN ('WORKSPACE_NOT_ACTIVE', 'ATTACHMENTS_UNAVAILABLE', 'MATERIAL_STALE', 'SENDER_POOL_STALE', 'SENDER_NOT_READY', 'CAPACITY_CONFIGURATION_INVALID', 'THREAD_EVIDENCE_MISSING', 'THREAD_EVIDENCE_AMBIGUOUS', 'THREAD_SENDER_CHANGED', 'DEFINITELY_UNACCEPTED_REVIEW', 'PROJECTION_RECONCILIATION_REQUIRED', 'DISPATCH_CONTRACT_CONFLICT')) AND "terminalReason" IS NULL AND "terminalAt" IS NULL) OR (state IN ('REPLIED','EXCLUDED','FINISHED') AND "holdReason" IS NULL AND "terminalReason" IN ('REPLY_RECEIVED', 'CREATOR_MISSING', 'CREATOR_DELETED', 'CAMPAIGN_CREATOR_MISSING', 'CAMPAIGN_CREATOR_DELETED', 'INVALID_STAGE', 'NON_EMAIL_CONTACT_METHOD', 'INVALID_EMAIL', 'DUPLICATE_CREATOR_EMAIL', 'SUPPRESSED_EMAIL', 'SEQUENCE_COMPLETED', 'NO_USABLE_AUTHORED_MESSAGE') AND "terminalAt" IS NOT NULL AND (state <> 'FINISHED' OR "nextAuthoredMessageIndex"="authoredMessageCount")), FALSE))`,
    );
  }
}
