export const MYAH_INBOX_DEFAULT_PAGE_SIZE = 25;
export const MYAH_INBOX_MAX_PAGE_SIZE = 100;
export const MYAH_INBOX_MAX_DRAFT_MARKDOWN_LENGTH = 100_000;
export const MYAH_INBOX_MAX_DRAFT_BLOCKNOTE_LENGTH = 1_000_000;
