export const AiChatErrorCode = {
  INCLUDED_USAGE_EXHAUSTED: 'INCLUDED_USAGE_EXHAUSTED',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  BILLING_CREDITS_EXHAUSTED: 'BILLING_CREDITS_EXHAUSTED',
  CONTEXT_WINDOW_EXCEEDED: 'CONTEXT_WINDOW_EXCEEDED',
  API_KEY_NOT_CONFIGURED: 'API_KEY_NOT_CONFIGURED',
  CONNECTION_LOST: 'CONNECTION_LOST',
} as const;
