import { FieldType, RelationType, defineObject } from 'twenty-sdk/define';

import { CREATOR_FIELD_UNIVERSAL_IDENTIFIERS } from 'src/constants/creator-field-universal-identifiers';
import {
  CAMPAIGN_CREATOR_FIELD_UNIVERSAL_IDENTIFIERS,
  CAMPAIGN_CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
  CREATOR_LIST_MEMBER_FIELD_UNIVERSAL_IDENTIFIERS,
  CREATOR_LIST_MEMBER_OBJECT_UNIVERSAL_IDENTIFIER,
  CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
  CREATOR_RELATION_FIELD_UNIVERSAL_IDENTIFIERS,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'creator',
  namePlural: 'creators',
  labelSingular: 'Creator',
  labelPlural: 'Creators',
  description: 'A creator profile imported from influencer discovery sources',
  icon: 'IconUserStar',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.name,
  fields: [
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.name,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Name',
      icon: 'IconUser',
      defaultValue: "''",
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.email,
      type: FieldType.TEXT,
      name: 'email',
      label: 'Email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.phone,
      type: FieldType.TEXT,
      name: 'phone',
      label: 'Phone',
      icon: 'IconPhone',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.location,
      type: FieldType.TEXT,
      name: 'location',
      label: 'Location',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.language,
      type: FieldType.TEXT,
      name: 'language',
      label: 'Language',
      icon: 'IconLanguage',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.profileType,
      type: FieldType.SELECT,
      name: 'profileType',
      label: 'Profile type',
      icon: 'IconUserCheck',
      defaultValue: "'CREATOR'",
      options: [
        {
          id: 'b30587ac-a851-5d1f-bbd7-3b6752bf6b06',
          value: 'CREATOR',
          label: 'Creator',
          position: 0,
          color: 'blue',
        },
        {
          id: '3da75a71-bb21-584b-a20f-a21f2a9ea385',
          value: 'BRAND',
          label: 'Brand',
          position: 1,
          color: 'purple',
        },
        {
          id: '1fad4603-50ec-5cf7-b3a1-91660cf401db',
          value: 'AGENCY',
          label: 'Agency',
          position: 2,
          color: 'orange',
        },
        {
          id: '6d675a09-a811-592e-a23d-868ff646e990',
          value: 'MEDIA',
          label: 'Media',
          position: 3,
          color: 'turquoise',
        },
      ],
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.creatorStatus,
      type: FieldType.SELECT,
      name: 'creatorStatus',
      label: 'Creator status',
      icon: 'IconProgressCheck',
      defaultValue: "'NEW'",
      options: [
        {
          id: '802d87dc-5d1f-5980-884c-b252f1bde49d',
          value: 'NEW',
          label: 'New',
          position: 0,
          color: 'gray',
        },
        {
          id: 'e88ede68-e4c7-52a6-8bfd-8503201d1b6b',
          value: 'REVIEWING',
          label: 'Reviewing',
          position: 1,
          color: 'blue',
        },
        {
          id: '9cd50629-da4e-5f32-be91-74ceb77c538e',
          value: 'QUALIFIED',
          label: 'Qualified',
          position: 2,
          color: 'green',
        },
        {
          id: '06d55c97-1366-59bc-a205-f679b8e6d8d9',
          value: 'CONTACTED',
          label: 'Contacted',
          position: 3,
          color: 'orange',
        },
        {
          id: 'd7f5c4f0-97a2-527c-91b0-86e42bc2349b',
          value: 'ARCHIVED',
          label: 'Archived',
          position: 4,
          color: 'red',
        },
      ],
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.source,
      type: FieldType.TEXT,
      name: 'source',
      label: 'Source',
      icon: 'IconDatabaseImport',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.sourceUrl,
      type: FieldType.TEXT,
      name: 'sourceUrl',
      label: 'Source URL',
      icon: 'IconLink',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.importSource,
      type: FieldType.TEXT,
      name: 'importSource',
      label: 'Import source',
      icon: 'IconFileImport',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.lastImportedAt,
      type: FieldType.DATE_TIME,
      name: 'lastImportedAt',
      label: 'Last imported at',
      icon: 'IconCalendarImport',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.hasLinkInBio,
      type: FieldType.BOOLEAN,
      name: 'hasLinkInBio',
      label: 'Has link in bio',
      icon: 'IconLink',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.hasBrandDeals,
      type: FieldType.BOOLEAN,
      name: 'hasBrandDeals',
      label: 'Has brand deals',
      icon: 'IconBriefcase',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.promotesAffiliateLinks,
      type: FieldType.BOOLEAN,
      name: 'promotesAffiliateLinks',
      label: 'Promotes affiliate links',
      icon: 'IconAffiliate',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.hasMerch,
      type: FieldType.BOOLEAN,
      name: 'hasMerch',
      label: 'Has merch',
      icon: 'IconShirt',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.linksInBio,
      type: FieldType.TEXT,
      name: 'linksInBio',
      label: 'Links in bio',
      icon: 'IconLinks',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.externalUrls,
      type: FieldType.TEXT,
      name: 'externalUrls',
      label: 'External URLs',
      icon: 'IconExternalLink',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.hashtagsUsed,
      type: FieldType.TEXT,
      name: 'hashtagsUsed',
      label: 'Hashtags used',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.categories,
      type: FieldType.TEXT,
      name: 'categories',
      label: 'Categories',
      icon: 'IconCategory',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.niches,
      type: FieldType.TEXT,
      name: 'niches',
      label: 'Niches',
      icon: 'IconTags',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.notes,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      icon: 'IconNotes',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramUrl,
      type: FieldType.TEXT,
      name: 'instagramUrl',
      label: 'Instagram URL',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramUsername,
      type: FieldType.TEXT,
      name: 'instagramUsername',
      label: 'Instagram username',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramBio,
      type: FieldType.TEXT,
      name: 'instagramBio',
      label: 'Instagram bio',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramFollowerCount,
      type: FieldType.NUMBER,
      name: 'instagramFollowerCount',
      label: 'Instagram follower count',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramEngagementPercent,
      type: FieldType.NUMBER,
      name: 'instagramEngagementPercent',
      label: 'Instagram engagement percent',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramMostRecentPostDate,
      type: FieldType.DATE,
      name: 'instagramMostRecentPostDate',
      label: 'Instagram most recent post date',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramMediaCount,
      type: FieldType.NUMBER,
      name: 'instagramMediaCount',
      label: 'Instagram media count',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramAvgLikes,
      type: FieldType.NUMBER,
      name: 'instagramAvgLikes',
      label: 'Instagram average likes',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramAvgComments,
      type: FieldType.NUMBER,
      name: 'instagramAvgComments',
      label: 'Instagram average comments',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramReelsPercent,
      type: FieldType.NUMBER,
      name: 'instagramReelsPercent',
      label: 'Instagram reels percent',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramReelsAvgViewCount,
      type: FieldType.NUMBER,
      name: 'instagramReelsAvgViewCount',
      label: 'Instagram reels average view count',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramPostingFrequencyRecentMonths,
      type: FieldType.NUMBER,
      name: 'instagramPostingFrequencyRecentMonths',
      label: 'Instagram posting frequency recent months',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramEstimatedIncomeMin,
      type: FieldType.NUMBER,
      name: 'instagramEstimatedIncomeMin',
      label: 'Instagram estimated income min',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.instagramEstimatedIncomeMax,
      type: FieldType.NUMBER,
      name: 'instagramEstimatedIncomeMax',
      label: 'Instagram estimated income max',
      icon: 'IconBrandInstagram',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokUrl,
      type: FieldType.TEXT,
      name: 'tiktokUrl',
      label: 'TikTok URL',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokUsername,
      type: FieldType.TEXT,
      name: 'tiktokUsername',
      label: 'TikTok username',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokBio,
      type: FieldType.TEXT,
      name: 'tiktokBio',
      label: 'TikTok bio',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokFollowerCount,
      type: FieldType.NUMBER,
      name: 'tiktokFollowerCount',
      label: 'TikTok follower count',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokMostRecentPostDate,
      type: FieldType.DATE,
      name: 'tiktokMostRecentPostDate',
      label: 'TikTok most recent post date',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokEngagementPercent,
      type: FieldType.NUMBER,
      name: 'tiktokEngagementPercent',
      label: 'TikTok engagement percent',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokVideoCount,
      type: FieldType.NUMBER,
      name: 'tiktokVideoCount',
      label: 'TikTok video count',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokPlayCountMedian,
      type: FieldType.NUMBER,
      name: 'tiktokPlayCountMedian',
      label: 'TikTok median play count',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokAvgLikes,
      type: FieldType.NUMBER,
      name: 'tiktokAvgLikes',
      label: 'TikTok average likes',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokAvgComments,
      type: FieldType.NUMBER,
      name: 'tiktokAvgComments',
      label: 'TikTok average comments',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokAvgDownloads,
      type: FieldType.NUMBER,
      name: 'tiktokAvgDownloads',
      label: 'TikTok average downloads',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.tiktokPostingFrequencyRecentMonths,
      type: FieldType.NUMBER,
      name: 'tiktokPostingFrequencyRecentMonths',
      label: 'TikTok posting frequency recent months',
      icon: 'IconBrandTiktok',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeUrl,
      type: FieldType.TEXT,
      name: 'youtubeUrl',
      label: 'YouTube URL',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeCustomUrl,
      type: FieldType.TEXT,
      name: 'youtubeCustomUrl',
      label: 'YouTube custom URL',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeTitle,
      type: FieldType.TEXT,
      name: 'youtubeTitle',
      label: 'YouTube title',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeDescription,
      type: FieldType.TEXT,
      name: 'youtubeDescription',
      label: 'YouTube description',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeTopicDetails,
      type: FieldType.TEXT,
      name: 'youtubeTopicDetails',
      label: 'YouTube topic details',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeSubscriberCount,
      type: FieldType.NUMBER,
      name: 'youtubeSubscriberCount',
      label: 'YouTube subscriber count',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeLastUploadDate,
      type: FieldType.DATE,
      name: 'youtubeLastUploadDate',
      label: 'YouTube last upload date',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeLastStreamUploadDate,
      type: FieldType.DATE,
      name: 'youtubeLastStreamUploadDate',
      label: 'YouTube last stream upload date',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeShortsPercentage,
      type: FieldType.NUMBER,
      name: 'youtubeShortsPercentage',
      label: 'YouTube Shorts percentage',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeVideoCount,
      type: FieldType.NUMBER,
      name: 'youtubeVideoCount',
      label: 'YouTube video count',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeEngagementPercent,
      type: FieldType.NUMBER,
      name: 'youtubeEngagementPercent',
      label: 'YouTube engagement percent',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeAvgViewsLong,
      type: FieldType.NUMBER,
      name: 'youtubeAvgViewsLong',
      label: 'YouTube average long views',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeAvgViewsShorts,
      type: FieldType.NUMBER,
      name: 'youtubeAvgViewsShorts',
      label: 'YouTube average Shorts views',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeAvgStreamViews,
      type: FieldType.NUMBER,
      name: 'youtubeAvgStreamViews',
      label: 'YouTube average stream views',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeAvgStreamDuration,
      type: FieldType.NUMBER,
      name: 'youtubeAvgStreamDuration',
      label: 'YouTube average stream duration',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubePostingFrequencyRecentMonths,
      type: FieldType.NUMBER,
      name: 'youtubePostingFrequencyRecentMonths',
      label: 'YouTube posting frequency recent months',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeEstimatedIncomeMin,
      type: FieldType.NUMBER,
      name: 'youtubeEstimatedIncomeMin',
      label: 'YouTube estimated income min',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.youtubeEstimatedIncomeMax,
      type: FieldType.NUMBER,
      name: 'youtubeEstimatedIncomeMax',
      label: 'YouTube estimated income max',
      icon: 'IconBrandYoutube',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitterUrl,
      type: FieldType.TEXT,
      name: 'twitterUrl',
      label: 'Twitter URL',
      icon: 'IconBrandX',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitterUsername,
      type: FieldType.TEXT,
      name: 'twitterUsername',
      label: 'Twitter username',
      icon: 'IconBrandX',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitterBio,
      type: FieldType.TEXT,
      name: 'twitterBio',
      label: 'Twitter bio',
      icon: 'IconBrandX',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitterFollowerCount,
      type: FieldType.NUMBER,
      name: 'twitterFollowerCount',
      label: 'Twitter follower count',
      icon: 'IconBrandX',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitterEngagementPercent,
      type: FieldType.NUMBER,
      name: 'twitterEngagementPercent',
      label: 'Twitter engagement percent',
      icon: 'IconBrandX',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitchUrl,
      type: FieldType.TEXT,
      name: 'twitchUrl',
      label: 'Twitch URL',
      icon: 'IconBrandTwitch',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitchUsername,
      type: FieldType.TEXT,
      name: 'twitchUsername',
      label: 'Twitch username',
      icon: 'IconBrandTwitch',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitchDisplayName,
      type: FieldType.TEXT,
      name: 'twitchDisplayName',
      label: 'Twitch display name',
      icon: 'IconBrandTwitch',
      isNullable: true,
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.twitchTotalFollowers,
      type: FieldType.NUMBER,
      name: 'twitchTotalFollowers',
      label: 'Twitch total followers',
      icon: 'IconBrandTwitch',
      isNullable: true,
    },
    {
      universalIdentifier:
        CREATOR_RELATION_FIELD_UNIVERSAL_IDENTIFIERS.listMemberships,
      type: FieldType.RELATION,
      name: 'listMemberships',
      label: 'List memberships',
      icon: 'IconListDetails',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        CREATOR_LIST_MEMBER_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        CREATOR_LIST_MEMBER_FIELD_UNIVERSAL_IDENTIFIERS.creator,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier:
        CREATOR_RELATION_FIELD_UNIVERSAL_IDENTIFIERS.campaignCreators,
      type: FieldType.RELATION,
      name: 'campaignCreators',
      label: 'Campaign creators',
      icon: 'IconTargetArrow',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        CAMPAIGN_CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        CAMPAIGN_CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.creator,
      universalSettings: {
        relationType: RelationType.ONE_TO_MANY,
      },
    },
    {
      universalIdentifier: CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.patreonUrl,
      type: FieldType.TEXT,
      name: 'patreonUrl',
      label: 'Patreon URL',
      icon: 'IconBrandPatreon',
      isNullable: true,
    },
  ],
});
