import {
  FieldType,
  OnDeleteAction,
  RelationType,
  defineObject,
} from 'twenty-sdk/define';

import {
  CAMPAIGN_CREATOR_FIELD_UNIVERSAL_IDENTIFIERS,
  CAMPAIGN_CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
  OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS,
  OUTREACH_ACTION_OBJECT_UNIVERSAL_IDENTIFIER,
  OUTREACH_STEP_FIELD_UNIVERSAL_IDENTIFIERS,
  OUTREACH_STEP_OBJECT_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: OUTREACH_ACTION_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'outreachAction',
  namePlural: 'outreachActions',
  labelSingular: 'Outreach Action',
  labelPlural: 'Outreach Actions',
  description: 'A scheduled or completed outreach action for a campaign creator',
  icon: 'IconSend',
  isSearchable: true,
  labelIdentifierFieldMetadataUniversalIdentifier:
    OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.name,
  fields: [
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.name, type: FieldType.TEXT, name: 'name', label: 'Name', icon: 'IconTag', defaultValue: "''" },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.campaignCreator,
      type: FieldType.RELATION,
      name: 'campaignCreator',
      label: 'Campaign Creator',
      icon: 'IconUserCheck',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        CAMPAIGN_CREATOR_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        CAMPAIGN_CREATOR_FIELD_UNIVERSAL_IDENTIFIERS.outreachActions,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'campaignCreatorId',
      },
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.outreachStep,
      type: FieldType.RELATION,
      name: 'outreachStep',
      label: 'Outreach Step',
      icon: 'IconListCheck',
      isNullable: true,
      relationTargetObjectMetadataUniversalIdentifier:
        OUTREACH_STEP_OBJECT_UNIVERSAL_IDENTIFIER,
      relationTargetFieldMetadataUniversalIdentifier:
        OUTREACH_STEP_FIELD_UNIVERSAL_IDENTIFIERS.actions,
      universalSettings: {
        relationType: RelationType.MANY_TO_ONE,
        onDelete: OnDeleteAction.SET_NULL,
        joinColumnName: 'outreachStepId',
      },
    },
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.channel, type: FieldType.TEXT, name: 'channel', label: 'Channel', icon: 'IconSend', isNullable: true },
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.status, type: FieldType.TEXT, name: 'status', label: 'Status', icon: 'IconProgress', isNullable: true },
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.scheduledAt, type: FieldType.DATE_TIME, name: 'scheduledAt', label: 'Scheduled at', icon: 'IconCalendarDue', isNullable: true },
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.completedAt, type: FieldType.DATE_TIME, name: 'completedAt', label: 'Completed at', icon: 'IconCircleCheck', isNullable: true },
    { universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.resultSummary, type: FieldType.TEXT, name: 'resultSummary', label: 'Result summary', icon: 'IconReportAnalytics', isNullable: true },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.subject,
      type: FieldType.TEXT,
      name: 'subject',
      label: 'Subject',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.body,
      type: FieldType.TEXT,
      name: 'body',
      label: 'Body',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.contentDigest,
      type: FieldType.TEXT,
      name: 'contentDigest',
      label: 'Content digest',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.recipientEmail,
      type: FieldType.TEXT,
      name: 'recipientEmail',
      label: 'Recipient email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.connectedAccountId,
      type: FieldType.TEXT,
      name: 'connectedAccountId',
      label: 'Connected account ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.messageChannelId,
      type: FieldType.TEXT,
      name: 'messageChannelId',
      label: 'Message channel ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.senderEmail,
      type: FieldType.TEXT,
      name: 'senderEmail',
      label: 'Sender email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.senderDisplayName,
      type: FieldType.TEXT,
      name: 'senderDisplayName',
      label: 'Sender display name',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.approvalBindingId,
      type: FieldType.TEXT,
      name: 'approvalBindingId',
      label: 'Approval binding ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.executionReceiptId,
      type: FieldType.TEXT,
      name: 'executionReceiptId',
      label: 'Execution receipt ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.providerDraftExternalId,
      type: FieldType.TEXT,
      name: 'providerDraftExternalId',
      label: 'Provider draft external ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.sentHeaderMessageId,
      type: FieldType.TEXT,
      name: 'sentHeaderMessageId',
      label: 'Sent header message ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.providerMessageExternalId,
      type: FieldType.TEXT,
      name: 'providerMessageExternalId',
      label: 'Provider message external ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.providerThreadExternalId,
      type: FieldType.TEXT,
      name: 'providerThreadExternalId',
      label: 'Provider thread external ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.messageId,
      type: FieldType.TEXT,
      name: 'messageId',
      label: 'Message ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.messageThreadId,
      type: FieldType.TEXT,
      name: 'messageThreadId',
      label: 'Message thread ID',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: OUTREACH_ACTION_FIELD_UNIVERSAL_IDENTIFIERS.inReplyTo,
      type: FieldType.TEXT,
      name: 'inReplyTo',
      label: 'In reply to',
      icon: 'IconMail',
      isNullable: true,
    },
  ],
});
