export const COMPOSIO_API_BASE_URL = 'https://backend.composio.dev/api/v3.1';

export const INSTAGRAM_LIST_ALL_CONVERSATIONS_TOOL_SLUG =
  'INSTAGRAM_LIST_ALL_CONVERSATIONS';
export const INSTAGRAM_LIST_ALL_MESSAGES_TOOL_SLUG =
  'INSTAGRAM_LIST_ALL_MESSAGES';

export type InstagramToolSlug =
  | typeof INSTAGRAM_LIST_ALL_CONVERSATIONS_TOOL_SLUG
  | typeof INSTAGRAM_LIST_ALL_MESSAGES_TOOL_SLUG;

export const MAX_MANUAL_DISCOVERY_LIMIT = 25;
