export const OUTBOUND_EMAIL_PROVIDER_REQUEST_TIMEOUT_MS = 30_000;
export const OUTBOUND_EMAIL_ATTEMPT_SAFETY_MARGIN_MS = 30_000;
export const OUTBOUND_EMAIL_UNKNOWN_AFTER_MS =
  OUTBOUND_EMAIL_PROVIDER_REQUEST_TIMEOUT_MS +
  OUTBOUND_EMAIL_ATTEMPT_SAFETY_MARGIN_MS;
