export enum ManagedEmailLifecycleAction {
  CANCEL_WARMUP_AT_PERIOD_END = 'CANCEL_WARMUP_AT_PERIOD_END',
  CANCEL_WARMUP_SUBSCRIPTION_PENDING = 'CANCEL_WARMUP_SUBSCRIPTION_PENDING',
  PAUSE_WARMUP_NOW = 'PAUSE_WARMUP_NOW',
  RESUME_WARMUP = 'RESUME_WARMUP',
  STOP_MAILBOX_AT_PERIOD_END = 'STOP_MAILBOX_AT_PERIOD_END',
  STOP_MAILBOX_SUBSCRIPTION_PENDING = 'STOP_MAILBOX_SUBSCRIPTION_PENDING',
  DISABLE_DOMAIN_RENEWAL = 'DISABLE_DOMAIN_RENEWAL',
  DISABLE_DOMAIN_SUBSCRIPTION_PENDING = 'DISABLE_DOMAIN_SUBSCRIPTION_PENDING',
}
